export const HIDE_LOADER = 'HIDE_LOADER';
export const SHOW_LOADER = 'SHOW_LOADER';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_GO_NEXT = 'SET_GO_NEXT';
