export const SET_SURVEY_QUESTIONS = 'SET_SURVEY_QUESTIONS';
export const SET_CORRECTIVE_QUESTIONS = 'SET_CORRECTIVE_QUESTIONS';
export const SET_SURVEY_SUBMITTED = 'SET_SURVEY_SUBMITTED';
export const CLEAR_SURVEY_DATA = 'CLEAR_SURVEY_DATA';
export const SAVE_CORRECTIVE_REQUESTS = 'SAVE_CORRECTIVE_REQUESTS';
export const SET_CORRECTIVE_QUESTIONS_FROM_API = 'SET_CORRECTIVE_QUESTIONS_FROM_API';
export const SHOW_INSPECTION_PAGE = 'SHOW_INSPECTION_PAGE';
