"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SHOW_INSPECTION_PAGE = exports.SET_CORRECTIVE_QUESTIONS_FROM_API = exports.SAVE_CORRECTIVE_REQUESTS = exports.CLEAR_SURVEY_DATA = exports.SET_SURVEY_SUBMITTED = exports.SET_CORRECTIVE_QUESTIONS = exports.SET_SURVEY_QUESTIONS = void 0;
exports.SET_SURVEY_QUESTIONS = 'SET_SURVEY_QUESTIONS';
exports.SET_CORRECTIVE_QUESTIONS = 'SET_CORRECTIVE_QUESTIONS';
exports.SET_SURVEY_SUBMITTED = 'SET_SURVEY_SUBMITTED';
exports.CLEAR_SURVEY_DATA = 'CLEAR_SURVEY_DATA';
exports.SAVE_CORRECTIVE_REQUESTS = 'SAVE_CORRECTIVE_REQUESTS';
exports.SET_CORRECTIVE_QUESTIONS_FROM_API = 'SET_CORRECTIVE_QUESTIONS_FROM_API';
exports.SHOW_INSPECTION_PAGE = 'SHOW_INSPECTION_PAGE';
//# sourceMappingURL=surveyConstants.js.map